php:
  image: php:7.4-apache
  container_name: meu-php2
  ports:
    - "8080:80"
    - "443:443"
  volumes:
    - /mnt/c/Users/rafael.l.gomes/Localhost/growcalendar/api:/var/www/html
  links:
    - db

db:
  image: mysql:latest
  container_name: meu-mysql-php2
  ports:
    - "3306:3306"
  volumes:
    - /var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root